import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Loading computed data 
erk_c = np.load("erk_C.npy")
erk_d = np.load("erk_D.npy")
perk_c = np.load("perk_C.npy")
perk_d = np.load("perk_D.npy")
pperk_c = np.load("pperk_C.npy")
pperk_d = np.load("pperk_D.npy")

mek_c = np.load("mek_C.npy")
mek_d = np.load("mek_D.npy")
pmek_c = np.load("pmek_C.npy")
pmek_d = np.load("pmek_D.npy")
ppmek_c = np.load("ppmek_C.npy")
ppmek_d = np.load("ppmek_D.npy")

raf_c = np.load("raf_C.npy")
raf_d = np.load("raf_D.npy")
praf_c = np.load("praf_C.npy")
praf_d = np.load("praf_D.npy")
ppraf_c = np.load("ppraf_C.npy")
ppraf_d = np.load("ppraf_D.npy")

time_c = np.load("time_C.npy")
time_d = np.load("time_D.npy")

plt.figure(1)
plt.plot(time_c,raf_c,label="raf")
plt.plot(time_c,praf_c,label="praf")
plt.plot(time_c,ppraf_c,label="ppraf")
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: RAF ")
plt.legend()
plt.savefig("case_raf")
"""
plt.figure(1)
plt.plot(time_d,raf_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: RAF ")
plt.savefig("caseD_raf")

plt.figure(2)
plt.plot(time_d,praf_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pRAF ")
plt.savefig("caseD_praf")

plt.figure(3)
plt.plot(time_d,ppraf_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppRAF ")
plt.savefig("caseD_ppraf")

plt.figure(4)
plt.plot(time_d,mek_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: MEK ")
plt.savefig("caseD_mek")

plt.figure(5)
plt.plot(time_d,pmek_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pMEK ")
plt.savefig("caseD_pmek")

plt.figure(6)
plt.plot(time_d,ppmek_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppMEK ")
plt.savefig("caseD_ppmek")

plt.figure(7)
plt.plot(time_d,erk_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ERK ")
plt.savefig("caseD_erk")

plt.figure(8)
plt.plot(time_d,perk_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pERK ")
plt.savefig("caseD_perk")

plt.figure(9)
plt.plot(time_d,pperk_d)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppERK ")
plt.savefig("caseD_pperk")

## Plotting part

fig, ax1 = plt.subplots(3,3)
plt.title("Case C")
ax1[0,0].plot(erk_c,time_c)
ax1[0,0].set_title("ERK")
ax1[0,1].plot(perk_c,time_c)
ax1[0,1].set_title("pERK")
ax1[0,2].plot(pperk_c,time_c)
ax1[0,2].set_title("ppERK")

ax1[1,0].plot(raf_c,time_c)
ax1[1,0].set_title("RAF")
ax1[1,1].plot(praf_c,time_c)
ax1[1,1].set_title("pRAF")
ax1[1,2].plot(ppraf_c,time_c)
ax1[1,2].set_title("ppRAF")

ax1[2,0].plot(mek_c,time_c)
ax1[2,0].set_title("MEK")
ax1[2,1].plot(pmek_c,time_c)
ax1[2,1].set_title("pMEK")
ax1[2,2].plot(ppmek_c,time_c)
ax1[2,2].set_title("ppMEK")

for ax in ax1.flat:
    ax.set(xlabel="time [min]", ylabel="concentration [nM]")

plt.savefig("bild3")

fig, ax = plt.subplots(figsize=(8,6))
case_c.plot(subplots=True,layout=(3,3),figsize=(10,6),ax=ax, xlabel="Time (min)", ylabel = "Concentration (nM)")
fig.subplots_adjust(top=0.8)
fig.align_ylabels()
plt.tight_layout()
plt.savefig("solution_case_C")

fig, ax = plt.subplots(figsize=(8,6))
case_d.plot(subplots=True,layout=(3,3),figsize=(10,6),ax=ax, xlabel="Time (min)", ylabel = "Concentration (nM)")
fig.subplots_adjust(top=0.8)
fig.align_ylabels()
plt.tight_layout()
plt.savefig("solution_case_D")


plt.plot(time_c,raf_c,label="raf")
plt.plot(time_c,praf_c,label="praf")
plt.plot(time_c,ppraf_c,label="ppraf")
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: RAF ")
plt.legend()
plt.show()


plt.figure(2)
plt.plot(time_c,praf_c)
plt.xlabel("time [min]")
plt.title("case C: pRAF ")
plt.ylabel("concentration [nM]")
plt.savefig("caseC_praf")

plt.figure(3)
plt.plot(time_c,ppraf_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: ppRAF ")
plt.savefig("caseC_ppraf")

plt.figure(4)
plt.plot(time_c,mek_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: MEK ")
plt.savefig("caseC_mek")

plt.figure(5)
plt.plot(time_c,pmek_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: pMEK ")
plt.savefig("caseC_pmek")

plt.figure(1)
plt.plot(time_c,ppmek_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: ppMEK ")
plt.savefig("caseC_ppmek")

plt.figure(2)
plt.plot(time_c,erk_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: ERK ")
plt.savefig("caseC_erk")

plt.figure(1)
plt.plot(time_c,perk_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: pERK ")
plt.savefig("caseC_perk")

plt.figure(2)
plt.plot(time_c,pperk_c)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case C: ppERK ")
plt.savefig("caseC_pperk")

plt.figure(1)
plt.plot(time,x1)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: RAF ")
plt.savefig("caseD_raf")

plt.figure(2)
plt.plot(time,x2)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pRAF ")
plt.savefig("caseD_praf")

plt.figure(3)
plt.plot(time,x3)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppRAF ")
plt.savefig("caseD_ppraf")

plt.figure(4)
plt.plot(time,x4)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: MEK ")
plt.savefig("caseD_mek")

plt.figure(5)
plt.plot(time,x5)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pMEK ")
plt.savefig("caseD_pmek")

plt.figure(6)
plt.plot(time,x6)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppMEK ")
plt.savefig("caseD_ppmek")

plt.figure(7)
plt.plot(time,x7)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ERK ")
plt.savefig("caseD_erk")

plt.figure(8)
plt.plot(time,x8)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: pERK ")
plt.savefig("caseD_perk")

plt.figure(9)
plt.plot(time,x9)
plt.xlabel("time [min]")
plt.ylabel("concentration [nM]")
plt.title("case D: ppERK ")
plt.savefig("caseD_pperk")
"""